/*
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.enbisys.avm.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets BuiltForm
 */
@JsonAdapter(BuiltForm.Adapter.class)
public enum BuiltForm {
  
  DETACHED("detached"),
  
  SEMI_DETACHED("semi_detached"),
  
  ENCLOSED_MID_TERRACE("enclosed_mid_terrace"),
  
  ENCLOSED_END_TERRACE("enclosed_end_terrace"),
  
  END_TERRACE("end_terrace"),
  
  MID_TERRACE("mid_terrace");

  private String value;

  BuiltForm(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BuiltForm fromValue(String value) {
    for (BuiltForm b : BuiltForm.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<BuiltForm> {
    @Override
    public void write(final JsonWriter jsonWriter, final BuiltForm enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BuiltForm read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return BuiltForm.fromValue(value);
    }
  }
}

