/*
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.enbisys.avm.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets LeaseholdOrFreehold
 */
@JsonAdapter(LeaseholdOrFreehold.Adapter.class)
public enum LeaseholdOrFreehold {
  
  FREEHOLD("freehold"),
  
  LEASEHOLD("leasehold");

  private String value;

  LeaseholdOrFreehold(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LeaseholdOrFreehold fromValue(String value) {
    for (LeaseholdOrFreehold b : LeaseholdOrFreehold.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LeaseholdOrFreehold> {
    @Override
    public void write(final JsonWriter jsonWriter, final LeaseholdOrFreehold enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LeaseholdOrFreehold read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LeaseholdOrFreehold.fromValue(value);
    }
  }
}

