/*
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.enbisys.avm.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * PropertyFeatures
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-12T12:39:15.489+07:00[Asia/Novosibirsk]")
public class PropertyFeatures {
  public static final String SERIALIZED_NAME_REQUIRED_FEATURES = "requiredFeatures";
  @SerializedName(SERIALIZED_NAME_REQUIRED_FEATURES)
  private RequiredFeatures requiredFeatures = null;

  public static final String SERIALIZED_NAME_ADDITIONAL_FEATURES = "additionalFeatures";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_FEATURES)
  private AdditionalFeatures additionalFeatures = null;

  public PropertyFeatures requiredFeatures(RequiredFeatures requiredFeatures) {
    this.requiredFeatures = requiredFeatures;
    return this;
  }

   /**
   * Get requiredFeatures
   * @return requiredFeatures
  **/
  @ApiModelProperty(required = true, value = "")
  public RequiredFeatures getRequiredFeatures() {
    return requiredFeatures;
  }

  public void setRequiredFeatures(RequiredFeatures requiredFeatures) {
    this.requiredFeatures = requiredFeatures;
  }

  public PropertyFeatures additionalFeatures(AdditionalFeatures additionalFeatures) {
    this.additionalFeatures = additionalFeatures;
    return this;
  }

   /**
   * Get additionalFeatures
   * @return additionalFeatures
  **/
  @ApiModelProperty(value = "")
  public AdditionalFeatures getAdditionalFeatures() {
    return additionalFeatures;
  }

  public void setAdditionalFeatures(AdditionalFeatures additionalFeatures) {
    this.additionalFeatures = additionalFeatures;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyFeatures propertyFeatures = (PropertyFeatures) o;
    return Objects.equals(this.requiredFeatures, propertyFeatures.requiredFeatures) &&
        Objects.equals(this.additionalFeatures, propertyFeatures.additionalFeatures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requiredFeatures, additionalFeatures);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyFeatures {\n");
    sb.append("    requiredFeatures: ").append(toIndentedString(requiredFeatures)).append("\n");
    sb.append("    additionalFeatures: ").append(toIndentedString(additionalFeatures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

