/*
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.enbisys.avm.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * type of property
 */
@JsonAdapter(PropertyType.Adapter.class)
public enum PropertyType {
  
  FLAT("flat"),
  
  SEMI_DETACHED_HOUSE("semi_detached_house"),
  
  DETACHED_HOUSE("detached_house"),
  
  TERRACED_HOUSE("terraced_house");

  private String value;

  PropertyType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PropertyType fromValue(String value) {
    for (PropertyType b : PropertyType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PropertyType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PropertyType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PropertyType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PropertyType.fromValue(value);
    }
  }
}

