/*
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.enbisys.avm.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * RequiredFeatures
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-12T12:39:15.489+07:00[Asia/Novosibirsk]")
public class RequiredFeatures {
  public static final String SERIALIZED_NAME_POSTCODE = "postcode";
  @SerializedName(SERIALIZED_NAME_POSTCODE)
  private String postcode;

  public static final String SERIALIZED_NAME_NEW_OR_RESALE = "newOrResale";
  @SerializedName(SERIALIZED_NAME_NEW_OR_RESALE)
  private NewOrResale newOrResale;

  public static final String SERIALIZED_NAME_FLOOR_LEVEL = "floorLevel";
  @SerializedName(SERIALIZED_NAME_FLOOR_LEVEL)
  private FloorLevel floorLevel;

  public static final String SERIALIZED_NAME_TOTAL_FLOOR_AREA_IN_SQF = "totalFloorAreaInSqf";
  @SerializedName(SERIALIZED_NAME_TOTAL_FLOOR_AREA_IN_SQF)
  private Integer totalFloorAreaInSqf;

  public static final String SERIALIZED_NAME_PROPERTY_TYPE = "propertyType";
  @SerializedName(SERIALIZED_NAME_PROPERTY_TYPE)
  private PropertyType propertyType;

  public static final String SERIALIZED_NAME_NUMBER_OF_ROOMS = "numberOfRooms";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_ROOMS)
  private Integer numberOfRooms;

  public RequiredFeatures postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Postcode
   * @return postcode
  **/
  @ApiModelProperty(example = "B1 1TB", required = true, value = "Postcode")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public RequiredFeatures newOrResale(NewOrResale newOrResale) {
    this.newOrResale = newOrResale;
    return this;
  }

   /**
   * Get newOrResale
   * @return newOrResale
  **/
  @ApiModelProperty(required = true, value = "")
  public NewOrResale getNewOrResale() {
    return newOrResale;
  }

  public void setNewOrResale(NewOrResale newOrResale) {
    this.newOrResale = newOrResale;
  }

  public RequiredFeatures floorLevel(FloorLevel floorLevel) {
    this.floorLevel = floorLevel;
    return this;
  }

   /**
   * Get floorLevel
   * @return floorLevel
  **/
  @ApiModelProperty(required = true, value = "")
  public FloorLevel getFloorLevel() {
    return floorLevel;
  }

  public void setFloorLevel(FloorLevel floorLevel) {
    this.floorLevel = floorLevel;
  }

  public RequiredFeatures totalFloorAreaInSqf(Integer totalFloorAreaInSqf) {
    this.totalFloorAreaInSqf = totalFloorAreaInSqf;
    return this;
  }

   /**
   * Floor area (sqf)
   * minimum: 50
   * maximum: 10000
   * @return totalFloorAreaInSqf
  **/
  @ApiModelProperty(example = "90", required = true, value = "Floor area (sqf)")
  public Integer getTotalFloorAreaInSqf() {
    return totalFloorAreaInSqf;
  }

  public void setTotalFloorAreaInSqf(Integer totalFloorAreaInSqf) {
    this.totalFloorAreaInSqf = totalFloorAreaInSqf;
  }

  public RequiredFeatures propertyType(PropertyType propertyType) {
    this.propertyType = propertyType;
    return this;
  }

   /**
   * Get propertyType
   * @return propertyType
  **/
  @ApiModelProperty(required = true, value = "")
  public PropertyType getPropertyType() {
    return propertyType;
  }

  public void setPropertyType(PropertyType propertyType) {
    this.propertyType = propertyType;
  }

  public RequiredFeatures numberOfRooms(Integer numberOfRooms) {
    this.numberOfRooms = numberOfRooms;
    return this;
  }

   /**
   * Get numberOfRooms
   * minimum: 1
   * maximum: 9
   * @return numberOfRooms
  **/
  @ApiModelProperty(example = "3", required = true, value = "")
  public Integer getNumberOfRooms() {
    return numberOfRooms;
  }

  public void setNumberOfRooms(Integer numberOfRooms) {
    this.numberOfRooms = numberOfRooms;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequiredFeatures requiredFeatures = (RequiredFeatures) o;
    return Objects.equals(this.postcode, requiredFeatures.postcode) &&
        Objects.equals(this.newOrResale, requiredFeatures.newOrResale) &&
        Objects.equals(this.floorLevel, requiredFeatures.floorLevel) &&
        Objects.equals(this.totalFloorAreaInSqf, requiredFeatures.totalFloorAreaInSqf) &&
        Objects.equals(this.propertyType, requiredFeatures.propertyType) &&
        Objects.equals(this.numberOfRooms, requiredFeatures.numberOfRooms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postcode, newOrResale, floorLevel, totalFloorAreaInSqf, propertyType, numberOfRooms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequiredFeatures {\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    newOrResale: ").append(toIndentedString(newOrResale)).append("\n");
    sb.append("    floorLevel: ").append(toIndentedString(floorLevel)).append("\n");
    sb.append("    totalFloorAreaInSqf: ").append(toIndentedString(totalFloorAreaInSqf)).append("\n");
    sb.append("    propertyType: ").append(toIndentedString(propertyType)).append("\n");
    sb.append("    numberOfRooms: ").append(toIndentedString(numberOfRooms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

