/*
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.enbisys.avm.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Valuation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-12T12:39:15.489+07:00[Asia/Novosibirsk]")
public class Valuation {
  public static final String SERIALIZED_NAME_MOST_PROBABLE_PRICE = "mostProbablePrice";
  @SerializedName(SERIALIZED_NAME_MOST_PROBABLE_PRICE)
  private Integer mostProbablePrice;

  public static final String SERIALIZED_NAME_PRICE_RANGE_FROM = "priceRangeFrom";
  @SerializedName(SERIALIZED_NAME_PRICE_RANGE_FROM)
  private Integer priceRangeFrom;

  public static final String SERIALIZED_NAME_PRICE_RANGE_TO = "priceRangeTo";
  @SerializedName(SERIALIZED_NAME_PRICE_RANGE_TO)
  private Integer priceRangeTo;

  public static final String SERIALIZED_NAME_CONFIDENCE = "confidence";
  @SerializedName(SERIALIZED_NAME_CONFIDENCE)
  private Integer confidence;

  public static final String SERIALIZED_NAME_PRICE_DISTRIBUTION = "priceDistribution";
  @SerializedName(SERIALIZED_NAME_PRICE_DISTRIBUTION)
  private List<ValuationPriceDistribution> priceDistribution = new ArrayList<ValuationPriceDistribution>();

  public Valuation mostProbablePrice(Integer mostProbablePrice) {
    this.mostProbablePrice = mostProbablePrice;
    return this;
  }

   /**
   * Predicted price, pound
   * @return mostProbablePrice
  **/
  @ApiModelProperty(example = "233000", value = "Predicted price, pound")
  public Integer getMostProbablePrice() {
    return mostProbablePrice;
  }

  public void setMostProbablePrice(Integer mostProbablePrice) {
    this.mostProbablePrice = mostProbablePrice;
  }

  public Valuation priceRangeFrom(Integer priceRangeFrom) {
    this.priceRangeFrom = priceRangeFrom;
    return this;
  }

   /**
   * Lower price boundary, pound
   * @return priceRangeFrom
  **/
  @ApiModelProperty(example = "230000", value = "Lower price boundary, pound")
  public Integer getPriceRangeFrom() {
    return priceRangeFrom;
  }

  public void setPriceRangeFrom(Integer priceRangeFrom) {
    this.priceRangeFrom = priceRangeFrom;
  }

  public Valuation priceRangeTo(Integer priceRangeTo) {
    this.priceRangeTo = priceRangeTo;
    return this;
  }

   /**
   * Higher price boundary, pound
   * @return priceRangeTo
  **/
  @ApiModelProperty(example = "235000", value = "Higher price boundary, pound")
  public Integer getPriceRangeTo() {
    return priceRangeTo;
  }

  public void setPriceRangeTo(Integer priceRangeTo) {
    this.priceRangeTo = priceRangeTo;
  }

  public Valuation confidence(Integer confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Probability (in percents) that actual price is within the specified boundaries
   * @return confidence
  **/
  @ApiModelProperty(example = "95", value = "Probability (in percents) that actual price is within the specified boundaries")
  public Integer getConfidence() {
    return confidence;
  }

  public void setConfidence(Integer confidence) {
    this.confidence = confidence;
  }

  public Valuation priceDistribution(List<ValuationPriceDistribution> priceDistribution) {
    this.priceDistribution = priceDistribution;
    return this;
  }

  public Valuation addPriceDistributionItem(ValuationPriceDistribution priceDistributionItem) {
    if (this.priceDistribution == null) {
      this.priceDistribution = new ArrayList<ValuationPriceDistribution>();
    }
    this.priceDistribution.add(priceDistributionItem);
    return this;
  }

   /**
   * Describes the probabilities (in percents) that actual price is within particular subranges
   * @return priceDistribution
  **/
  @ApiModelProperty(value = "Describes the probabilities (in percents) that actual price is within particular subranges")
  public List<ValuationPriceDistribution> getPriceDistribution() {
    return priceDistribution;
  }

  public void setPriceDistribution(List<ValuationPriceDistribution> priceDistribution) {
    this.priceDistribution = priceDistribution;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Valuation valuation = (Valuation) o;
    return Objects.equals(this.mostProbablePrice, valuation.mostProbablePrice) &&
        Objects.equals(this.priceRangeFrom, valuation.priceRangeFrom) &&
        Objects.equals(this.priceRangeTo, valuation.priceRangeTo) &&
        Objects.equals(this.confidence, valuation.confidence) &&
        Objects.equals(this.priceDistribution, valuation.priceDistribution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mostProbablePrice, priceRangeFrom, priceRangeTo, confidence, priceDistribution);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Valuation {\n");
    sb.append("    mostProbablePrice: ").append(toIndentedString(mostProbablePrice)).append("\n");
    sb.append("    priceRangeFrom: ").append(toIndentedString(priceRangeFrom)).append("\n");
    sb.append("    priceRangeTo: ").append(toIndentedString(priceRangeTo)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    priceDistribution: ").append(toIndentedString(priceDistribution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

