/*
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.enbisys.avm.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets WallType
 */
@JsonAdapter(WallType.Adapter.class)
public enum WallType {
  
  CAVITY_WALL("cavity_wall"),
  
  COB("cob"),
  
  GRANITE_OR_WHIN("granite_or_whin"),
  
  PARK_HOME_WALL("park_home_wall"),
  
  SANDSTONE("sandstone"),
  
  SOLID_BRICK("solid_brick"),
  
  SYSTEM_BUILD("system_build"),
  
  TIMBER_FRAME("timber_frame");

  private String value;

  WallType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WallType fromValue(String value) {
    for (WallType b : WallType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WallType> {
    @Override
    public void write(final JsonWriter jsonWriter, final WallType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WallType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WallType.fromValue(value);
    }
  }
}

